In [2]:
import pandas as pd

In [3]:
users = pd.read_csv('tables/users.csv')
movies = pd.read_csv('tables/movies.csv')
watch_history = pd.read_csv('tables/watch_history.csv')

In [9]:
users.head()

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,subscription_start_date,is_active,monthly_spend,primary_device,household_size,created_at
0,user_00001,figueroajohn@example.org,Erica,Garza,43.0,Male,USA,Massachusetts,North Jefferyhaven,Basic,2024-04-08,True,36.06,Laptop,1.0,2023-04-01 14:40:50.540242
1,user_00002,blakeerik@example.com,Joshua,Bernard,38.0,Male,USA,Texas,North Noahstad,Premium+,2024-05-24,True,14.59,Desktop,2.0,2024-10-10 15:39:11.030515
2,user_00003,smiller@example.net,Barbara,Williams,32.0,Female,USA,Michigan,Traciebury,Standard,2023-09-22,False,11.71,Desktop,3.0,2024-06-29 14:27:49.560875
3,user_00004,mitchellclark@example.com,Chelsea,Ferguson,11.0,Male,USA,Ohio,South Noah,Standard,2024-08-21,True,28.56,Laptop,2.0,2023-04-11 01:01:59.614841
4,user_00005,richard13@example.net,Jason,Foster,21.0,Female,USA,Arizona,West Donald,Standard,2024-10-28,True,9.54,Desktop,6.0,2025-04-12 19:59:30.137806

In [5]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 10300 entries, 0 to 10299
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  10300 non-null  str
 1   email                    10300 non-null  str
 2   first_name               10300 non-null  str
 3   last_name                10300 non-null  str
 4   age                      9071 non-null   float64
 5   gender                   9476 non-null   str
 6   country                  10300 non-null  str
 7   state_province           10300 non-null  str
 8   city                     10300 non-null  str
 9   subscription_plan        10300 non-null  str
 10  subscription_start_date  10300 non-null  str
 11  is_active                10300 non-null  bool
 12  monthly_spend            9283 non-null   float64
 13  primary_device           10300 non-null  str
 14  household_size           8755 non-null   float64
 15  created_at               10300 non-null  str
dtypes: bool(1), float64(3), str(12)
memory usage: 1.2 MB

In [10]:
movies.head()

,movie_id,title,content_type,genre_primary,genre_secondary,release_year,duration_minutes,rating,language,country_of_origin,imdb_rating,production_budget,box_office_revenue,number_of_seasons,number_of_episodes,is_netflix_original,added_to_platform,content_warning
0,movie_0001,Dragon Legend,Stand-up Comedy,History,Thriller,2014,35.0,TV-Y,French,Japan,NaN,NaN,NaN,NaN,NaN,False,2023-08-07,False
1,movie_0002,Storm Warrior,Stand-up Comedy,Sci-Fi,NaN,2017,37.0,PG,Japanese,USA,3.3,NaN,NaN,NaN,NaN,False,2022-01-28,True
2,movie_0003,Fire Family,Movie,Drama,NaN,2003,142.0,TV-MA,English,USA,8.5,2114120.0,NaN,NaN,NaN,False,2021-05-04,True
3,movie_0004,Our Princess,Documentary,Sci-Fi,NaN,2011,131.0,NC-17,Japanese,USA,5.3,NaN,NaN,NaN,NaN,False,2022-11-26,False
4,movie_0005,Warrior Mission,Documentary,Sport,Mystery,2015,91.0,TV-G,English,USA,3.1,NaN,NaN,NaN,NaN,False,2023-06-15,False

In [7]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1040 entries, 0 to 1039
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   movie_id             1040 non-null   str
 1   title                1040 non-null   str
 2   content_type         1040 non-null   str
 3   genre_primary        1040 non-null   str
 4   genre_secondary      373 non-null    str
 5   release_year         1040 non-null   int64
 6   duration_minutes     1040 non-null   float64
 7   rating               1040 non-null   str
 8   language             1040 non-null   str
 9   country_of_origin    1040 non-null   str
 10  imdb_rating          890 non-null    float64
 11  production_budget    365 non-null    float64
 12  box_office_revenue   331 non-null    float64
 13  number_of_seasons    289 non-null    float64
 14  number_of_episodes   321 non-null    float64
 15  is_netflix_original  1040 non-null   bool
 16  added_to_platform    1040 non-null   str
 17  content_warning      1040 non-null   bool
dtypes: bool(2), float64(6), int64(1), str(9)
memory usage: 132.2 KB

In [11]:
watch_history.head()

,session_id,user_id,movie_id,watch_date,device_type,watch_duration_minutes,progress_percentage,action,quality,location_country,is_download,user_rating
0,session_000001,user_07271,movie_0511,2025-11-13,Tablet,63.9,34.6,completed,HD,USA,False,NaN
1,session_000002,user_00861,movie_0588,2025-02-26,Laptop,120.1,44.2,started,HD,USA,False,NaN
2,session_000003,user_05391,movie_0694,2024-12-15,Desktop,572.1,84.7,started,HD,Canada,False,1.0
3,session_000004,user_05192,movie_0234,2024-09-30,Desktop,395.3,89.9,completed,SD,USA,False,5.0
4,session_000005,user_05735,movie_0390,2024-08-04,Tablet,14.6,6.2,completed,HD,USA,False,NaN

In [8]:
watch_history.info()

<class 'pandas.DataFrame'>
RangeIndex: 105000 entries, 0 to 104999
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   session_id              105000 non-null  str
 1   user_id                 105000 non-null  str
 2   movie_id                105000 non-null  str
 3   watch_date              105000 non-null  str
 4   device_type             105000 non-null  str
 5   watch_duration_minutes  92668 non-null   float64
 6   progress_percentage     96486 non-null   float64
 7   action                  105000 non-null  str
 8   quality                 105000 non-null  str
 9   location_country        105000 non-null  str
 10  is_download             105000 non-null  bool
 11  user_rating             21097 non-null   float64
dtypes: bool(1), float64(3), str(8)
memory usage: 8.9 MB